# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UiPathPack@6
  inputs:
    projectJsonPath: 'project.json'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    outputType: 'Process'
    orchestratorConnection: 'AzureDev'
    traceLevel: 'None'
- task: UiPathDeploy@6
  inputs:
    orchestratorConnection: 'AzureDev'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Kavina'
    traceLevel: 'None'